import type { Metadata } from "next";
import Image from "next/image";
import { CheckCircle2, Eye, Flag } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { CtaBand } from "@/components/cta-band";

export const metadata: Metadata = { title: "About Us", description: "Learn about Kreston Infra Projects, its founders, mission, vision, and quality-driven construction approach." };

const mission = ["Deliver projects of all scales with uncompromising quality and reliability", "Plan, design, and execute construction works with precision and transparency", "Use approved and high-quality materials across all stages", "Provide professional guidance and end-to-end client support", "Ensure timely delivery and complete client satisfaction"];

export default function AboutPage() {
  return <>
    <PageHero eyebrow="About us" title="Built on clarity, quality, and commitment." description="A professionally managed civil and infrastructure construction company headquartered in Madhapur, Hyderabad." />
    <section className="bg-white py-20 sm:py-28 lg:py-32"><div className="mx-auto grid max-w-site gap-14 px-5 sm:px-8 lg:grid-cols-2 lg:items-center lg:gap-20"><div><SectionHeading eyebrow="Our company" title="Professional construction. Premium execution." /><div className="mt-7 space-y-5 text-[15px] leading-7 text-ink/62"><p>Kreston Infra Projects delivers comprehensive solutions across residential and infrastructure sectors. Operating across Telangana, the company executes projects of all scales with a structured, quality-driven approach.</p><p>Its end-to-end construction services include civil works, infrastructure development, fabrication and laying, interior and exterior works, and plumbing contracting.</p><p>With carefully sourced materials, disciplined supervision, and strong internal coordination, Kreston Infra Projects works to ensure durable, safe, and value-driven project outcomes.</p></div></div><div className="relative aspect-[4/3] overflow-hidden bg-mist image-zoom"><Image src="/images/company-residential.png" alt="Residential building shown in Kreston Infra Projects company profile" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><div className="absolute bottom-0 left-0 bg-copper px-6 py-5 text-white"><p className="font-display text-2xl font-medium">Established 2021</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-white/65">Hyderabad, Telangana</p></div></div></div></section>
    <section className="bg-mist py-20 sm:py-28"><div className="mx-auto max-w-site px-5 sm:px-8"><SectionHeading eyebrow="Leadership" title="Hands-on direction from the founders." copy="Technical understanding and committed involvement shape Kreston’s professional culture and disciplined approach to project delivery." /><div className="mt-12 grid gap-px bg-ink/10 md:grid-cols-2"><article className="bg-white p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-copper">Co-founder</p><h3 className="mt-4 font-display text-3xl font-semibold tracking-tight">Yahya Mohammed</h3><p className="mt-5 text-sm leading-7 text-ink/55">Part of the founding leadership team bringing strong experience in civil engineering and construction execution.</p></article><article className="bg-white p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-copper">Co-founder</p><h3 className="mt-4 font-display text-3xl font-semibold tracking-tight">Shaikh Mohammed Imran</h3><p className="mt-5 text-sm leading-7 text-ink/55">Part of the founding leadership team guiding the company through hands-on involvement and a commitment to quality.</p></article></div></div></section>
    <section className="bg-ink py-20 text-white sm:py-28 lg:py-32"><div className="mx-auto grid max-w-site gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:gap-20"><div><div className="flex h-12 w-12 items-center justify-center bg-copper"><Flag className="h-5 w-5" /></div><h2 className="mt-7 font-display text-4xl font-medium tracking-[-.04em]">Our mission</h2><div className="mt-7 space-y-4">{mission.map(item => <p key={item} className="flex gap-3 text-sm leading-6 text-white/65"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-copper" />{item}</p>)}</div></div><div className="border-t border-white/15 pt-12 lg:border-l lg:border-t-0 lg:pl-20 lg:pt-0"><div className="flex h-12 w-12 items-center justify-center bg-copper"><Eye className="h-5 w-5" /></div><h2 className="mt-7 font-display text-4xl font-medium tracking-[-.04em]">Our vision</h2><p className="mt-7 text-lg leading-8 text-white/65">To be a trusted and leading construction company delivering high-quality residential and infrastructure projects through engineering excellence, professional execution, and long-term value creation.</p></div></div></section>
    <CtaBand />
  </>;
}
