import type { Metadata } from "next";
import Image from "next/image";
import { ArrowDown } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { CtaBand } from "@/components/cta-band";
import { capabilities } from "@/lib/data";

export const metadata: Metadata = { title: "Why Kreston", description: "Discover Kreston's planning, inspections, supervision, technical verification, coordination, and quality-focused execution." };

export default function CapabilitiesPage() { return <><PageHero eyebrow="Why Kreston" title="Reliable execution is a process." description="Kreston connects planning, technical verification, site supervision, and stakeholder coordination at every project stage." image="/images/site-engineering.png" />
  <section className="bg-white py-20 sm:py-28 lg:py-32"><div className="mx-auto grid max-w-site gap-14 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><SectionHeading eyebrow="Our approach" title="Seven controls. One standard." copy="A structured and process-driven approach supports quality, coordination, and reliable execution across all project stages." /><div className="relative mt-10 aspect-[4/5] overflow-hidden image-zoom"><Image src="/images/technical-planning.png" alt="Technical drawing verification and planning" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div></div><div className="space-y-3">{capabilities.map((item,index)=>{const Icon=item.icon; return <article key={item.title} className="group grid grid-cols-[auto_1fr_auto] items-start gap-4 border border-ink/10 p-5 transition hover:border-copper hover:bg-mist sm:gap-6 sm:p-7"><span className="grid h-11 w-11 place-items-center bg-copper/10 text-copper"><Icon className="h-5 w-5" strokeWidth={1.5}/></span><div><h2 className="font-display text-xl font-semibold tracking-tight">{item.title}</h2><p className="mt-2 text-sm leading-6 text-ink/55">{item.text}</p></div><span className="font-display text-sm font-semibold text-ink/25">0{index+1}</span></article>})}</div></div></section>
  <section className="bg-ink py-20 text-white sm:py-28"><div className="mx-auto max-w-site px-5 sm:px-8"><SectionHeading eyebrow="Connected delivery" title="From a line on paper to a result on site." light align="center" /><div className="mt-14 grid md:grid-cols-3">{[{n:"01",t:"Plan & verify",d:"Understand the brief, review drawings, and align specifications."},{n:"02",t:"Coordinate & supervise",d:"Connect engineers, site teams, owners, and ongoing inspections."},{n:"03",t:"Execute & control",d:"Build with disciplined supervision and quality-focused execution."}].map((s,i)=><div key={s.n} className="relative border border-white/12 p-8 md:border-r-0 last:md:border-r"><p className="text-xs font-bold text-copper">{s.n}</p><h3 className="mt-8 font-display text-2xl font-medium">{s.t}</h3><p className="mt-3 text-sm leading-6 text-white/55">{s.d}</p>{i<2&&<ArrowDown className="absolute -bottom-4 left-1/2 z-10 h-8 w-8 -translate-x-1/2 rounded-full bg-copper p-2 md:-right-4 md:bottom-auto md:left-auto md:top-1/2 md:-translate-y-1/2 md:translate-x-0 md:-rotate-90"/>}</div>)}</div></div></section><CtaBand /></> }
